image: node:7.0.0

cache:
  paths:
    - node_modules/

before_script:
  - npm install --silent -g phantomjs-prebuilt ember-cli jshint bower

test:
  stage: test
  script:
    - npm install --silent && bower --allow-root install
    - ember test

stages:
  - test
